apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      initContainers:
        - name: wait-for-rabbitmq
          image: busybox:1.28
          command: ['sh', '-c', "until nc -zv rabbitmq 5672; do echo waiting for rabbitmq; sleep 2; done"]
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      containers:
        - name: order-service
          image: avurlerby/order-service:45431d60dc1d6e85ad7ee7f56ddbfd65d408b58b
          ports:
            - containerPort: 3004
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3004"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: ORDERS_DB_URL
            - name: AUTH_SERVICE_URL
              value: "http://auth:3002"
            - name: PRODUCT_SERVICE_URL
              value: "http://product-service:3003"
            - name: RABBIT_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: RABBIT_URL

---

apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: boutique
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: ClusterIP
