apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: boutique
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
        - name: product-service
          image: avurlerby/product-service:39fc95cc79377acd97f674f718a3fd1799b2b0d0
          ports:
            - containerPort: 3003
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: NODE_ENV
              value: development
            - name: PORT
              value: "3003"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: boutique-secrets
                  key: PRODUCTS_DB_URL
            - name: OTLP_ENDPOINT
              value: "http://jaeger:4318/v1/traces"

---

apiVersion: v1
kind: Service
metadata:
  name: product-service
  namespace: boutique
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
