apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      vaultUrl: "https://crud-kv-24cc.vault.azure.net/"
      authType: ServicePrincipal
      tenantId: "dcbf7382-8381-4638-9a5b-17998c16d54a"
      authSecretRef:
        clientId:
          name: azure-sp-credentials
          key: client-id
          namespace: external-secrets
        clientSecret:
          name: azure-sp-credentials
          key: client-secret
          namespace: external-secrets
