apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: azure-kv
spec:
  provider:
    azurekv:
      vaultUrl: "https://crud-kv.vault.azure.net/"
      authType: ServicePrincipal
      tenantId: "f09536f4-5988-40db-808d-eabbdfbb5e63"
      authSecretRef:
        clientId:
          name: azure-sp-credentials
          key: client-id
          namespace: default
        clientSecret:
          name: azure-sp-credentials
          key: client-secret
          namespace: default
