apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: boutique-secrets
  namespace: boutique
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-kv
    kind: ClusterSecretStore
  target:
    name: boutique-secrets
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef:
        key: boutique-POSTGRES-DB
    - secretKey: POSTGRES_USER
      remoteRef:
        key: boutique-POSTGRES-USER
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: boutique-POSTGRES-PASSWORD
    - secretKey: AUTH_DB_URL
      remoteRef:
        key: boutique-AUTH-DB-URL
    - secretKey: PRODUCTS_DB_URL
      remoteRef:
        key: boutique-PRODUCTS-DB-URL
    - secretKey: ORDERS_DB_URL
      remoteRef:
        key: boutique-ORDERS-DB-URL
    - secretKey: USERS_DB_URL
      remoteRef:
        key: boutique-USERS-DB-URL
    - secretKey: RABBIT_URL
      remoteRef:
        key: boutique-RABBIT-URL
    - secretKey: RABBITMQ_USER
      remoteRef:
        key: boutique-RABBITMQ-USER
    - secretKey: RABBITMQ_PASSWORD
      remoteRef:
        key: boutique-RABBITMQ-PASSWORD
    - secretKey: SMTP_HOST
      remoteRef:
        key: boutique-SMTP-HOST
    - secretKey: SMTP_PORT
      remoteRef:
        key: boutique-SMTP-PORT
    - secretKey: SMTP_USER
      remoteRef:
        key: boutique-SMTP-USER
    - secretKey: SMTP_PASS
      remoteRef:
        key: boutique-SMTP-PASS
    - secretKey: EMAIL_FROM
      remoteRef:
        key: boutique-EMAIL-FROM
