apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator-crds
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://prometheus-community.github.io/helm-charts'
    chart: kube-prometheus-stack
    targetRevision: 85.0.1
    helm:
      values: |
        prometheus:
          enabled: true
        grafana:
          enabled: true
          adminPassword: admin
          service:
            type: ClusterIP
        alertmanager:
          enabled: true
        prometheusOperator:
          enabled: true
          manageCrds: true
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - Validate=false
